### ISSUE TITLE
Build for raspberry pi image is failing

### ISSUE THREAD

**Issue by khassel** [bastilimbach/docker-MagicMirror#1]
Hi, 
there are only 2 versions in docker store, latest and alpine. raspberry is missing.
Thanks,
Karsten.

**Comment by khassel** [comment]
O.K., found this a moment ago:
"The raspberry image is currently failing on Docker Hub. I'm on it."
(from https://github.com/MichMich/MagicMirror/pull/856 )

**Comment by khassel** [comment]
Looked into this, something with syntax of "docker-entrypoint.sh" seems to be wrong. Thats strange, this works with other images.
Substituted for testing purpuses
ENTRYPOINT ["/opt/magic_mirror/docker-entrypoint.sh"]
with
ENTRYPOINT ["node", "serveronly"]
and this works.

**Comment by khassel** [comment]
Yesterday I pushed this to docker: https://store.docker.com/community/images/karsten13/mm_hyp
See Dockerfile below. This works.

FROM hypriot/rpi-node:latest

ENV NODE_ENV production
ENV MM_PORT 8080

RUN apt-get update
RUN apt-get upgrade

# needed later in run command:
RUN apt-get -y install dos2unix

# not needed:
#RUN apt-get -y install curl wget git build-essential unzip

# only for having nano as editor:
RUN apt-get -y install nano

# only needed for the module MMM-NetworkScanner:
RUN apt-get -y install arp-scan

# getting MagicMirror from github
RUN cd /opt  
RUN git clone https://github.com/MichMich/MagicMirror.git /opt/magic_mirror/
WORKDIR /opt/magic_mirror
RUN cd /opt/magic_mirror
RUN git checkout origin/develop

# install (without param the mirror remains black):
RUN npm install --unsafe-perm

# copy sample to real config:
RUN cp config/config.js.sample config/config.js

# create copies for unmount:
COPY /modules unmount_modules
COPY /config unmount_config

RUN ["dos2unix", "docker-entrypoint.sh"]
RUN ["chmod", "+x", "docker-entrypoint.sh"]

EXPOSE $MM_PORT
ENTRYPOINT ["/opt/magic_mirror/docker-entrypoint.sh"]

**Comment by bastilimbach** [comment]
Yeah, it's pretty strange. That's the reason I couldn't get it to work. I don't know where exactly the error is. I'll try the base image `hypriot/rpi-node:latest` which you used. Will look into this tomorrow.

**Comment by bastilimbach** [comment]
Fixed with the workaround of using travis instead of docker hub to build the arm version. See [travis file](https://github.com/bastilimbach/docker-MagicMirror/blob/master/.travis.yml)
