### ISSUE TITLE
MagicMirror update

### ISSUE THREAD

**Issue by MrNonoss** [bastilimbach/docker-MagicMirror#14]
Hi @bastilimbach 
Thanks for your great docker image.

Could you please update it to the latest version?

Thank you a lot

**Comment by bastilimbach** [comment]
The image gets updated automatically every day by Travis CI. The last build succeeded successfully and did get pushed to Docker Hub. Did you try removing and redownloading the image? What version are you getting?

**Comment by bastilimbach** [comment]
Please check out my [comment on a previous issue](https://github.com/bastilimbach/docker-MagicMirror/issues/12#issuecomment-411670631) and see if this fixes you issue. Maybe there is really a problem which I just can't reproduce.

**Comment by MrNonoss** [comment]
Thanks for your reply,

I wasn't aware of the automatic update. I just checked the date of the last build (7 months) and assumed it wasn't updated.

In fact, thetrouble came from my side. For an unknown reason, some modules like weather and calendar were stuck. a reboot of the docker image and the raspberry did the trick.

Sorry for the burden.

**Comment by bastilimbach** [comment]
Perfect! The last build time is very confusing indeed. Unfortunately, I can't change that. You need to look at the "Last pushed" date 👍
