### ISSUE TITLE
ERRO[0472] error waiting for container: context canceled

### ISSUE THREAD

**Issue by Sisikon** [bastilimbach/docker-MagicMirror#17]
Hi

I just run the docker run -d \ commands.
It started to pull from bastilimbach/docker-magicmirror (all are completed).
After that it startet with "Status: Downloaded newer image for bastilimbach/docker-magicmirror:latest and prompt with the error message:
ERRO[0472] error waiting for container: context canceled

Any idea ?

**Comment by bastilimbach** [comment]
This is a strange error. I think it has to do with you docker installation. Could you please provide the output of `docker info` and some system information?

**Comment by bastilimbach** [comment]
Closing this due to no response. Please feel free to reopen the issue.

**Comment by slimcdk** [comment]
`context canceled` is a message produced by the default go context library when a deadline is exceeded (usually meaning a timeout)
