### ISSUE TITLE
black magicmirror-screen running latest-image under Windows10

### ISSUE THREAD

**Issue by khassel** [bastilimbach/docker-MagicMirror#2]
Hi,
getting a black screen running your latest-image under Windows10. This issue is already described here: https://forum.magicmirror.builders/topic/2333/docker-setup-is-not-working
Building your image locally with "RUN npm install --unsafe-perm" is working.
Thanks,
Karsten.

**Comment by bastilimbach** [comment]
Sorry for my late response. That's interesting. I'll test this and update the Dockerfiles. I've never heard of `--unsafe-perm`.
