### ISSUE TITLE
News module not updating

### ISSUE THREAD

**Issue by bachoo786** [bastilimbach/docker-MagicMirror#23]
Hi @bastilimbach 

Everything works fine. What I noticed that the news module does not update with the latest news unless I was to refresh the browser.

Is that a bug or?

**Comment by idoodler** [comment]
@bachoo786 Hey, may you provide logs from your browser. I am using this project in a project of mine and everything work regarding the News module.

Also this project is basically a wrapper around the awesome MagicMirror project. You may find help in the [official forum](https://forum.magicmirror.builders).

**Comment by bastilimbach** [comment]
@idoodler Thanks for your help! 

@bachoo786 Logs & your config would be really helpful. Maybe something is wrong with your configuration. Maybe @idoodler can provide their working config.

**Comment by idoodler** [comment]
Sure, @bachoo786 I guess you mean the default `newsfeed` module.

Checkout my module config:

```
            {
                module: "newsfeed",
                position: "bottom_bar",
                config: {
                    feeds: [
                        {
                            title: "PNP",
                            url: "http://www.pnp.de/_export/rss/nachrichten/stadt_landkreis_passau/passau_land/index.rss"
                        }
                    ],
                    showSourceTitle: true,
                    showPublishDate: true,
                    updateInterval:  20000
                }
            }
```

**Comment by idoodler** [comment]
@bachoo786 Ping

**Comment by bastilimbach** [comment]
@bachoo786 If you are still having problems with the configuration please feel free to reopen the issue.
