### ISSUE TITLE
Container always restarts

### ISSUE THREAD

**Issue by Disane87** [bastilimbach/docker-MagicMirror#24]
Installed it by the command

>docker run  -d \
	--publish 8080:8080 \
	--restart always \
	--volume ~/magic_mirror/config:/opt/magic_mirror/config \
	--volume ~/magic_mirror/modules:/opt/magic_mirror/modules \
	--name magic_mirror \
	bastilimbach/docker-magicmirror

Modified the port 80 to 8080 because I've already have some listens on 80.
Actually it is restarting every time with the following message in `docker logs magic_mirror`

> exec user process caused "exec format error"

Docker info:
``` 
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.59-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 927.3MiB
Name: WohnzimmerPi3
ID: TQ2P:VVP7:KNUD:EZ5Y:EUOF:O5EZ:FPLF:3HOT:A4VT:VHBI:WI43:LM7K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by henry74** [comment]
Need to pull the pi image as follows:

> docker run -d 
> --publish 8080:8080 
> --restart always 
> --volume ~/magic_mirror/config:/opt/magic_mirror/config 
> --volume ~/magic_mirror/modules:/opt/magic_mirror/modules 
> --name magic_mirror 
> bastilimbach/docker-magicmirror:`raspberry`

Note: It looks like this image is way behind the github repo so not sure you should use it other than testing

**Comment by Disane87** [comment]
> Need to pull the pi image as follows:
> 
> > docker run -d
> > --publish 8080:8080
> > --restart always
> > --volume ~/magic_mirror/config:/opt/magic_mirror/config
> > --volume ~/magic_mirror/modules:/opt/magic_mirror/modules
> > --name magic_mirror
> > bastilimbach/docker-magicmirror:`raspberry`
> 
> Note: It looks like this image is way behind the github repo so not sure you should use it other than testing

Yeah, thank you! Just saw that too, that I use a false image. The age of this is not really problematic, cause I can update mm. Thank you!
