### ISSUE TITLE
Wrong time zone on calendar events

### ISSUE THREAD

**Issue by magpern** [bastilimbach/docker-MagicMirror#27]
I have the docker running on a ubuntu server. All time zones and time is correct.
The RPi showing the magic mirror from the docker host is also set with correct time zone.
The clock in magic mirror is correct, but calendar events are off by a few hours. Event is set as 07:45 CEST but shows as 09:45

I solved this by supplying the docker with a TZ=Europe/Stockholm environment variable. Perhaps the readme file should reflect this.

This is a working docker-compose snipplet for magic mirror docker
```javascript
  magicmirror:
    container_name: magicmirror
    image: bastilimbach/docker-magicmirror
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/magic_mirror/config:/opt/magic_mirror/config
      - ~/magic_mirror/modules:/opt/magic_mirror/modules
    ports:
      - 8888:8080
```

**Comment by bastilimbach** [comment]
Issue #15 is probably related to this one.
It might actually not be a bad idea to include a small section in the README. Do you maybe want to create a PR for this?

**Comment by bastilimbach** [comment]
A "Frequently asked questions" section with "My timezone is wrong, how can I fix this?" would be quite useful. This could also be expanded in the future.

**Comment by bastilimbach** [comment]
Thanks again for the PR! 🎉
