### ISSUE TITLE
"2832 Commits behind the master branch"

### ISSUE THREAD

**Issue by simonsolberg** [bastilimbach/docker-MagicMirror#30]
Hi, 

I keep getting this complaint that I'm many commits behind the master branch: 

![image](https://user-images.githubusercontent.com/31542525/71771640-d23e5680-2f3e-11ea-9aea-28ab19bf2e48.png)

But on Docker hub the images update regularly, latest was today, and I'm sure I'm running the latest image.
![image](https://user-images.githubusercontent.com/31542525/71771650-00239b00-2f3f-11ea-8729-6d2d894226dc.png)

Is the Docker hub image building from this repository? If it is; why isn't this repository being updated?

**Comment by khassel** [comment]
see https://github.com/MichMich/MagicMirror/issues/1855

**Comment by bastilimbach** [comment]
Thanks @khassel for pointing to the issue. Seems like we can't do much here. Therefore I will close this issue. Please keep an eye out on the referenced issue @simonsolberg .
