### ISSUE TITLE
Kubernetes example wanted?

### ISSUE THREAD

**Issue by klaernie** [bastilimbach/docker-MagicMirror#39]
Hi there,

as my homelab nowadays has Kubernetes running, I migrated my magic mirror setup into it.

First of all: @bastilimbach thanks for packaging the docker image! Works nicely!

Would there be interest in the configuration I used to get my two mirrors hosted in server-only mode in Kubernetes?

A rough overview:
- a configmap for per-mirror configs (containing `config.js` and both `custom.css` and `main.css` (the latter only because I have to)
- one NFS volume to store the `modules/`
- one deployment / service pair to run the container for each mirror instance
- one shared nginx to host the calendar ICS (fed from the outside with vdirsyncer)

It's all running nicely now, but the things that bug me are:
- the default MM modules will not get updated with the image (and option to always overwrite them would be nice)
- ~I have to carry `main.css` in the configmaps, as mounting the configmap to `css/` would prevent access to the `main.css` from the image.~ (fixed see below)

If there is interest in my setup I can post them here, but also feel free to tag me ask questions in this issue.

**Comment by khassel** [comment]
I'm interested. Did a first hack a year ago but without a good solution for the modules ...

As this repo is restricted to `serveronly` I did a docker setup too which supports also the second use case (running the mm on the screen of the pi). I don't want to entice users away from here, this is the official mm-docker-repo, but I solved you're first point (override default modules) [there](https://gitlab.com/khassel/magicmirror#default-modules) already.

**Comment by bastilimbach** [comment]
Sure! Documentation/Samples are always welcome. However I wouldn’t add such information into the readme as this is really detailed and setup specific. Maybe we create a GitHub Wiki page for this. We could also add more docker compose samples there etc.

What’s your opinion?

**Comment by klaernie** [comment]
My first instinct would be to put it into a `docs/k8s/` folder inside the repo itself. That is much easier to open PRs if anything needs changing and can have its own `README.md` describing the relations and considerations.

**Comment by klaernie** [comment]
so, at least for `main.css` I found the right way to do it: `subPath` mounting my config volume.

**Comment by bastilimbach** [comment]
@klaernie I just checked how GitHub Wikis are working under the hood. I thought this would be just some files in a folder like GitHub Pages. But no. It's persisted in a separate git repo which makes it super hard to contribute -.-

Therefore I would agree with you. Let's create a `docs` folder with a summary in the top-level `README.md`. Then in every folder, we can have specific readme files 👍

**Comment by khassel** [comment]
meanwhile I investigated several hours in this and wrote a helm chart for MagicMirror. You can find the first version [here](https://gitlab.com/khassel/magicmirror-helm).

This setup uses normal `config.js` and `custom.css` files in subfolders. Modules have to be specified as list in the `values.yaml`, they are cloned (incl. `npm install`) at start.

**Comment by bastilimbach** [comment]
@klaernie any updates? Are you still interested in creating a PR for the documentation? Otherwise I’ll close the issue.

No problem if you currently do not find the time. Just wanted to check if there is still the desire to create a PR in the future😊

**Comment by skandragon** [comment]
I would like to see your setup before I go and make mine :)

I have a small Raspberry Pi 4 cluster in my basement, and would like to give it a job.

**Comment by klaernie** [comment]
Yes, still planning on writing it up. Just work stuff got in the way. Sorry to leave you hanging.

**Comment by bastilimbach** [comment]
Absolutely no problem 😊 I’ll leave this issue open as long as you want 👍

**Comment by DrSoops** [comment]
I too am curious as to how you are treating different modules.
Say you have some heavy weight module like facial recognition, did you find a way to have that run as a stand alone pod (with opencv and other dependencies) or does everything still have to be run on a single pod that has all these dependencies packaged into the image.

**Comment by klaernie** [comment]
@DrSoops actually everything in my setup runs in a single pod (per instance). The PR is now up, so you can take a look how I did it. Also in my use case the device running the display for the mirror and the kubernetes cluster are not the same - my entire approach is based on taking the cpu load from my display devices (a Beaglebone Black and a RaspberryPi) and moving it onto a beefy x86 server.

So I don't know, how facial recognition is implemented (I don't have this need), but I assume you need to feed the camera somehow. Guessing that you use [paviro/MMM-Facial-Recognition](https://github.com/paviro/MMM-Facial-Recognition), you'd need to first get the webcam into the pod, or add an network camera feed input module for it to work. But then you can easily move the entire server-side of magic mirror, which includes the face detection, onto a beefy machine.

**Comment by DrSoops** [comment]
Single pod with one beefy server as a backbone. That makes sense and works, I was just hoping to be able to somehow self contain the cluster with spreading the load on extra Pis/Jetsons.
