### ISSUE TITLE
Error trying to run it in server only mode

### ISSUE THREAD

**Issue by henriquearake1** [bastilimbach/docker-MagicMirror#41]
### 
Hello, I'm trying to run MagicMirror² in server only mode using the following command line
`docker run -d publish 80:8080 restart always volume ~/magic_mirror/config:/opt/magic_mirror/config volume ~/magic_mirror/modules:/opt/magic_mirror/modules volume /etc/localtime:/etc/localtime:ro name magic_mirror  bastilimbach/docker-magicmirror`
but it isn't working. This is the error message: "Unable to find image 'publish:latest' locally
docker: Error response from daemon: pull access denied for publish, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'."

I re-installed Docker and GIT, but the error remains the same.

I'm using a windows 10 machine.

**Comment by henriquearake1** [comment]
Newbie error, guys. I forgot to type "--"

**Comment by bastilimbach** [comment]
Thanks for coming back and closing the issue! You‘re surely not the first one to forget the double dashes 😂
