### ISSUE TITLE
Spectacularily fails on Raspberry Pi Zero

### ISSUE THREAD

**Issue by berlincount** [bastilimbach/docker-MagicMirror#54]
Hello,

and thanks for this awesome image!

Sadly, node explodes on Raspberry Pi Zero with the arm/v7 image, with `node` dying a `SIGILL` death - because only a `v6l` is employed :-/

Maybe make an additional image available, or even use a v6l node instead of v7?

Cheers!

**Comment by Legion2** [comment]
we can add the additional architecture to the image build.

**Comment by berlincount** [comment]
nah, the node.js doesn't support that, so I'm closing this without solution, too tall order imho

**Comment by berlincount** [comment]
(Invalid Instruction due to different CPU instruction set)
