### ISSUE TITLE
This device is not allowed to access your mirror, again

### ISSUE THREAD

**Issue by acejacek** [bastilimbach/docker-MagicMirror#6]
Spoiler alert: I have `ipWhitelist: []` in `config.js`.

I have strange problem with access to MagicMirror run from Docker container. After few restarts it welcomes me with well know:

_This device is not allowed to access your mirror. 
Please check your config.js or config.js.sample to change this._

I'm using your run command, which maps correctly `--volume ~/magic_mirror/config:/opt/magic_mirror/config`.

When I get into running container with `docker exec -ti magic_mirror bash` I can see, that config file is exectly the same `config.js` I have outside the container.

So, is it some black magic with docking, or it's MagicMirror problem? Or it's me?

**Comment by bastilimbach** [comment]
Could you post your `config.js` file?

**Comment by acejacek** [comment]
I dug into log files. `docker logs magic_mirror` shows:
```
Starting MagicMirror: v2.1.2
Loading config ...
  [... bla bla bla ...]
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
  [...cut some more...]
Ready to go! Please point your browser to: http://localhost:8080
Access denied to IP address: 0.0.0.0/0
Access denied to IP address: 0.0.0.0/0
```
I modified my `ipWhitelist: []` to `ipWhitelist: ["0.0.0.0/0"]` and now all works OK. Bit strange, because `config.js.sample` says: "Set [] to allow all IP addresses".

 Sorry for false alarm, issue closed.

**Comment by bastilimbach** [comment]
That's strange. Possibly an issue with magic mirror. `0.0.0.0/0` should be included if you set `ipWhitelist: []`. Glad you could solve it 👍
