### ISSUE TITLE
Modules help

### ISSUE THREAD

**Issue by samabsalom** [bastilimbach/docker-MagicMirror#8]
Hello, 
love the docker image ! how do we install extra commands (such as ping for MMM-NetworkScanner ) and allow it be maintained through updates?

Thanks!
Sam

**Comment by bastilimbach** [comment]
Hi @samabsalom,
thank you. I hope it helps. The best option for you is to fork this repo and add the needed dependencies to these lines:
https://github.com/bastilimbach/docker-MagicMirror/blob/f244dfd8459db9f4d285b896b4022b9a4cc20f0c/Dockerfile#L14-L17

If you want to have `ping` installed for `MMM-NetworkScanner` it would look something like this:
```bash
RUN apt-get update \
  && apt-get -qy install dos2unix iputils-ping \
  && dos2unix /opt/docker-entrypoint.sh \
  && chmod +x /opt/docker-entrypoint.sh
```
*(Notice the addition of `iputils-ping`)*

The `docker-magicmirror:latest` Dockerfile is based on debian so you can use `apt-get` to install all the dependencies.

After all your additions you need to build the Dockerfile and upload the image to use it. Remember to build the image at least every month to get the newest magic mirror updates.

Maybe I could include some dependencies of popular MM-Modules and publish this version under a different tag (eg. `docker-magicmirror:advanced`). Do you know a way to look up the most popular ones?

**Comment by samabsalom** [comment]
Thanks for your help! Not sure of popular ones but i'll flick through and see what are used. Ill fork the repo now and maybe submit a PR with the additions
Sam

**Comment by BenRoe** [comment]
@samabsalom you can also go into the docker container and install ping via apt-get 
```bash
// find the image id
docker images

// open bash inside the docker container
docker run -it IMAGE-ID bash

// install ping
apt-get update && apt-get install ping
```
