### ISSUE TITLE
Missing yarn-or-npm

### ISSUE THREAD

**Issue by cslamar** [bastilimbach/docker-MagicMirror#9]
When building from the master of MagicMirror, the dependency for `yarn-or-npm` is miss from the main dependencies in `package.json`, and the build fails looking for the `yon` command.  You can get around this by installing `yarn-or-npm` as a step before doing the `npm install --unsafe-perm --silent`.

This doesn't effect if you change the branch of MagicMirror to develop, as it seems to no longer use `yarn-or-npm`.

**Comment by bastilimbach** [comment]
@cslamar this is a known issue of MagicMirror. I already pushed a fix to the main repo ([#1250](https://github.com/MichMich/MagicMirror/pull/1250)). It should work again when the `develop` branch gets merged into `master`. I think this should be the case at the end of this month.

**Comment by bastilimbach** [comment]
Another workaround is to remove this line:
https://github.com/bastilimbach/docker-MagicMirror/blob/f244dfd8459db9f4d285b896b4022b9a4cc20f0c/Dockerfile#L3

**Comment by bastilimbach** [comment]
As it seems that the merge [will still take some time](https://github.com/MichMich/MagicMirror/blob/develop/CHANGELOG.md#240---unreleased-current-develop-branch) I included a temporary workaround to fix the build: [997e2f0](https://github.com/bastilimbach/docker-MagicMirror/commit/24fa51314f20120e3d2549b3fcf35c3b65195e1a)

**Comment by bastilimbach** [comment]
Fixed with 0d92ce00bbf014606ebf784bdf77a52c5124ef62
